/**
 * 为了解决反序列化的问题，各种符号并不使用“Symbol”类型
 */

export const vdType = {
  SERIAL_PORT: 'SERIAL_PORT',
  TCP: 'TCP'
}

export const vdState = {
  STOPED: 'STOPED',
  STARTING: 'STARTING',
  DEVICE_CONNECTING: 'DEVICE_CONNECTING',
  DEVICE_RECONNECTING: 'DEVICE_RECONNECTING',
  SERVER_CONNECTING: 'SERVER_CONNECTING',
  SERVER_RECONNECTING: 'SERVER_RECONNECTING',
  RUNNING: 'RUNNING',
  HEARTBEAT: 'HEARTBEAT',
  STOPPING: 'STOPPING'
}
